### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by hasezoey** [OoDeLally/typegoose-inheritance-bug#1]
*coming from https://github.com/typegoose/typegoose/issues/80, and investigating the issue*

here is a collection of things i wanted to ask, they might change
- why is `@typegoose/typegoose` listed as a ***dev***Dependencie?
- why are you using `ts-node-dev` and not the normal?

---

things i noticed are definitely wrong:
- you use the types wrong, like in 
https://github.com/OoDeLally/typegoose-inheritance-bug/blob/d31c5925060e4c5d175cb447bcf3b270f1979aff/src/index.ts#L19-L22
it would be needed to wrap in `DocumentType<Class>`for accurate types
- you use the type for the models wrong too, like in
https://github.com/OoDeLally/typegoose-inheritance-bug/blob/d31c5925060e4c5d175cb447bcf3b270f1979aff/src/bar.ts#L18
you would need to wrap it in `ReturnModelType<typeof Class>` to have accurate types
- in `bar.ts` (where the class for the error is), you are using an "virtual-populate", and point to a field to look for to compare the foreign field to, which is named `fooId`, and is missing

---

-> please correct these and or explain why using it, thanks

**Comment by hasezoey** [comment]
btw for the type issues, we have an documentation https://typegoose.github.io/typegoose/

- https://typegoose.github.io/typegoose/docs/types/document/
- https://typegoose.github.io/typegoose/docs/types/returnModelType/

and sorry that there is no virtual-documentation [*yet*](https://typegoose.github.io/typegoose/docs/decorators/prop/#virtuals)

**Comment by hasezoey** [comment]
Update for you, when travis & github have finished building, virtual documentation should be available under https://typegoose.github.io/typegoose/docs/virtuals

**Comment by OoDeLally** [comment]
Ok I've modified the few points that you suggested. These were good suggestions. Thank you.

While adding the automatic creation of `BaseFoo` and `Bar` documents 
```
 const myFoo = await BaseFooModel.create({});
```
I had the following error:
```Error [MongooseError]: document must have an _id before saving```

I assumed that mongoose would get the `_id` from the db. I noticed that settings `_id` as a `@prop` on a document impedes this, and results in the above error.
Following this, I notice that the examples provided in `typegoose` never have `_id` as `@prop`. I haven't realized how critical this was.

Now, the funny part: when removing `@prop` from the `_id`, the original error
```
If you are populating a virtual, you must set the localField and foreignField options```
disappeared!

It seems like adding this `@prop` to `_id` messes with a large number of things. And the error message I got does not help at all figure out what is wrong.

Can you confirm that making `_id` as `@prop` is definitively a bad thing?
Are you able to figure out why this results into this strange error message, which doesn't sounds remotely related to an `_id`?

If this is really the cause of my error, may I suggest that `typegoose` crashes in this case with an error something like `'_id' cannot be a @prop` or such.

Thank you

**Comment by hasezoey** [comment]
> I haven't realized how critical this was.

"critical" to have it or "critical" to not have it?

---

> _id messes with a large number of things

no this is intended how mongoose should work

---

for the ID things, and default properties, we have default classes that you can extend from, they provide the types needed https://typegoose.github.io/typegoose/guides/defaultClasses/
-> in this case, "Base" would be the one you want

---

mongoose implicitly always adds the "_id" field, it is always needed *before* saving to the database, when you dont want an "_id" field, dont use mongoose

---

what i noticed now, please dont use `getModelForClass<Bar, any>` (the generic definitions), those are made automatically, they are public, because they cant be set to "private"

---

> Can you confirm that making _id as @prop is definitively a bad thing?

yes, it is a bad thing, thanks to the error, when you want to set the "_id" field to ... say of type "String", you would just add the type to the class, and mongoose automatically handles it

---

> If this is really the cause of my error, may I suggest that typegoose crashes in this case with an error something like '_id' cannot be a @prop or such.

yes, will make in 6.1.0, to not break anything in a patch release
